Lock down @types/react-autosuggest to 10.1.2 until UI team can investigate. 10.1.4 produces: --[ FAILURE: @bentley/ui-core ]---------------------[ 1 minute 59.2 seconds ]--
src/ui-core/autosuggest/AutoSuggest.tsx(259,7): error TS2322: Type '(e: React.ChangeEvent<HTMLInputElement>) => void' is not assignable to type '(event: FormEvent<HTMLElement>, params: ChangeEvent) => void'.
  Types of parameters 'e' and 'event' are incompatible.
    Type 'FormEvent<HTMLElement>' is not assignable to type 'ChangeEvent<HTMLInputElement>'.
      Types of property 'target' are incompatible.
        Type 'EventTarget' is not assignable to type 'EventTarget & HTMLInputElement'.
          Type 'EventTarget' is missing the following properties from type 'HTMLInputElement': accept, align, alt, autocomplete, and 284 more.