Merged PR 40262: Fix webpack preferring ES module version of node-fetch over CommonJS version.
Fix webpack preferring ES module version of node-fetch over CommonJS version.

This should fix an edge case where packages that provide multiple module types can have inconsistent behavior when webpacked.

Basically, a library we are using (@azure/ms-rest-js) is calling `require("node-fetch")`, so the module resolution algorithm has to look at node-fetch's package.json file to see what that actually means.  However, even when targeting node, webpack has a slightly different module resolution behavior in that (by default) it prefers ES6/Harmony modules over CommonJS, so it's looking at the "module" field in node-fetch's package.json instead of the "main" field (as node does).

This seems to be causing "TypeError: fetch is not a function" errors, because when webpack bundles/transpiles the ES6 module instead of the CommonJS version, the caller would really need to use `require("node-fetch").default`.  Since we can't change the ms-rest-js package, we can instead change our webpack config to always prefer CommonJS modules instead.

See https://github.com/bitinn/node-fetch/issues/450#issuecomment-494475397 for more info.