@bentley/imodeljs-native 2.16.0 (#1220)
* call element, model, and aspect events from native code. (#1186)

* move update and delete events to native

* move calling events on element, model, aspects to native code

* doc

* documentation

* add tests for element/model callbacks

* clean up test

* update doucumentation

* rush change

* update doc

* added onSubModel events. Add tests for ElementAspect.onXxx methods

* add tests for Element.onSubModelXxx

* test cleanup

* @bentley/imodeljs-native 2.16.0

* Lock down @types/react-autosuggest to 10.1.2 until UI team can
investigate.
10.1.4 produces:
--[ FAILURE: @bentley/ui-core ]---------------------[ 1 minute 59.2 seconds ]--

src/ui-core/autosuggest/AutoSuggest.tsx(259,7): error TS2322: Type '(e: React.ChangeEvent<HTMLInputElement>) => void' is not assignable to type '(event: FormEvent<HTMLElement>, params: ChangeEvent) => void'.
  Types of parameters 'e' and 'event' are incompatible.
    Type 'FormEvent<HTMLElement>' is not assignable to type 'ChangeEvent<HTMLInputElement>'.
      Types of property 'target' are incompatible.
        Type 'EventTarget' is not assignable to type 'EventTarget & HTMLInputElement'.
          Type 'EventTarget' is missing the following properties from type 'HTMLInputElement': accept, align, alt, autocomplete, and 284 more.

* Lock classnames down to 2.2.6 until UI team can investigate.
2.3.1 produces:
--[ FAILURE: @bentley/ui-framework ]------------------------[ 31.87 seconds ]--

src/ui-framework/cursor/cursorpopup/CursorPopup.tsx(176,24): error TS2349: This expression is not callable.
  Type 'typeof import("D:/js/s/imodeljs/common/temp/node_modules/.pnpm/registry.npmjs.org/classnames/2.3.1/node_modules/classnames/index")' has no call signatures.
src/ui-framework/messages/InputField.tsx(79,74): error TS2349: This expression is not callable.
  Type 'typeof import("D:/js/s/imodeljs/common/temp/node_modules/.pnpm/registry.npmjs.org/classnames/2.3.1/node_modules/classnames/index")' has no call signatures.
src/ui-framework/toolbar/GroupButtonItem.tsx(196,24): error TS2349: This expression is not callable.
  Type 'typeof import("D:/js/s/imodeljs/common/temp/node_modules/.pnpm/registry.npmjs.org/classnames/2.3.1/node_modules/classnames/index")' has no call signatures.
src/ui-framework/toolbar/GroupItem.tsx(367,24): error TS2349: This expression is not callable.
  Type 'typeof import("D:/js/s/imodeljs/common/temp/node_modules/.pnpm/registry.npmjs.org/classnames/2.3.1/node_modules/classnames/index")' has no call signatures.

* Fix release tags.

* Skip failing test. Behavior has changed.

* formatting change to hopefully get ADO running again.

* extract-api again.

Co-authored-by: Caleb Shafer <31107829+calebmshafer@users.noreply.github.com>
Co-authored-by: DaumantasJankauskas <47949861+DaumantasJankauskas@users.noreply.github.com>
Co-authored-by: imodeljs-admin <38288322+imodeljs-admin@users.noreply.github.com>
Co-authored-by: Dan East <51122937+DanEastBentley@users.noreply.github.com>
Co-authored-by: Keith Bentley <33296803+kabentley@users.noreply.github.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Co-authored-by: bsteinbk <65047615+bsteinbk@users.noreply.github.com>
Co-authored-by: Robert Lukasonok <70327485+roluk@users.noreply.github.com>
Co-authored-by: Bill Goehrig <33036725+wgoehrig@users.noreply.github.com>
Co-authored-by: MarcNeely <36053767+MarcNeely@users.noreply.github.com>
Co-authored-by: bbastings <65233531+bbastings@users.noreply.github.com>
Co-authored-by: Michel D'Astous <mdastous-bentley@users.noreply.github.com>
Co-authored-by: ramanujam-raman <32458710+ramanujam-raman@users.noreply.github.com>
Co-authored-by: Grigas <35135765+grigasp@users.noreply.github.com>
Co-authored-by: lerzeel2 <69574322+lerzeel2@users.noreply.github.com>
Co-authored-by: NancyMcCallB <45079789+NancyMcCallB@users.noreply.github.com>
Co-authored-by: Ivan Kok <ivanjayk@gmail.com>
Co-authored-by: swbsi <69857376+swbsi@users.noreply.github.com>
Co-authored-by: RBBentley <ray.bentley@bentley.com>
Co-authored-by: Ray.Bentley <rbbentley@users.noreply.github.com>
Co-authored-by: scsewall <36768600+scsewall@users.noreply.github.com>
Co-authored-by: Diego Pinate <4107657+diegopinate@users.noreply.github.com>
Co-authored-by: EarlinLutz <69321059+EarlinLutz@users.noreply.github.com>
Co-authored-by: roopksaini <68084841+roopksaini@users.noreply.github.com>
Co-authored-by: roopksaini <roopksaini@users.noreply.github.com>
Co-authored-by: hnn0003 <18196761+hnn0003@users.noreply.github.com>
Co-authored-by: Saulius Skliutas <24278440+saskliutas@users.noreply.github.com>
Co-authored-by: markschlosseratbentley <47000437+markschlosseratbentley@users.noreply.github.com>